name: ken_dala
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  scroll_to_index: ^3.0.1
  provider: ^6.1.2
  collection: ^1.18.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  story_view: ^0.16.5
  rect_getter: ^1.1.0
  shared_preferences: ^2.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  build_runner: ^2.4.11
  path_provider: ^2.1.4
  animations: ^2.0.11
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  skeletonizer: ^1.4.2
  flutter_launcher_icons: ^0.14.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  material_floating_search_bar_2: ^0.5.0
  flutter_native_splash: ^2.4.1
  mask_text_input_formatter: ^2.9.0
  connectivity_plus: ^6.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.1

#flutter_launcher_icons:
#  image_path_android: "assets/images/icon_a.jpg"
#  image_path_ios: "assets/images/icon_a.jpg"
#  background_color_android: "#ffffff"
#  android: true
#  ios: true
#  adaptive_icon_background: "assets/images/icon_a.jpg"
#  adaptive_icon_foreground: "assets/images/icon_a.jpg"
#  adaptive_icon_foreground_inset: 16
#  adaptive_icon_monochrome: "assets/images/icon_a.jpg"
#  min_sdk_android: 21
#  remove_alpha_ios: true
#  background_color_ios: "#ffffff"

flutter_launcher_icons:
  image_path_android: "assets/images/icon"
  image_path_ios: "assets/images/icon"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon"
  adaptive_icon_foreground_inset: 16
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_android: "#FFFFFFFF"
  background_color_ios: "#FFFFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_white.jpg

  android_12:
    color: "#FFFFFF"
    image: assets/images/logo_white.jpg
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/fonts/inter/
    - assets/fonts/pregoo/
    - assets/images/icon.png


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
          weight: 800
    - family: Prego
      fonts:
        - asset: assets/fonts/pregoo/PregoLight.ttf
          weight: 300
        - asset: assets/fonts/pregoo/PregoRegular.ttf
          weight: 400
        - asset: assets/fonts/pregoo/PregoBold.ttf
          weight: 700
